# KnockBack by Skull3x #

Power: 4.0
# Amount of KnockBack, default is 4.0

Level: world
# Level or level's where knockback will be activated, default is level 'world'

# ThankYou for installing KnockBack <3
# Github: http://github.com/Skull3x/KnockBack
